### ISSUE TITLE
Strange ADC values

### ISSUE THREAD

**Issue by mrgithub** [G6EJD/ESP32-ADC-Accuracy-Improvement-function#1]
I'm using the basic example code (https://www.youtube.com/watch?v=RlKMJknsNpo).

I've hooked up a mic (Electret Microphone Amplifier - MAX4466 with Adjustable Gain ID) to the ADC.  

The ADC gives fluctuating values between 0 - 400 ish when unconnected.  With the microphone plugged in the ADC gives values around the 1700-1800s.  It does not change when speaking.  

I thought it was broken so connected up an oscilliscope and after fiddling around with oscilliscope settings I can see the mic is outputting a waveform when speaking in the vicinity.

Why doesn't the ADC give correlating changes in values?  

Mic:  
VCC - connected to 3v off the wemos board;  
GND - connected to GND on wemos board; 
OUT - connected to pin 13 as per example code.  (I've changed this around to different pins in case it was dodgy but similar behaviour).

**Comment by G6EJD** [comment]
This is not a software issue, it’s due to hardware and voltage and impedance matching. I’ve looked the the standard MAX4466 circuit (they do vary) and can see its output bias is 1.65 volts. The maximum input to the ESP32 ADC is 1.0 volts, so that explains what your seeing. 
1. Test the ADC pin with nothing connected using your finger you should see plenty of fluctuations.
2. Test the microphone with nothing connected to it’s output, scope ok and ideal, there should be fluctuations when you tap the microphone or speak.
3. Now solve the mismatch by AC coupling the microphone output to the ADC input. Just about any value capacitor will do, the lower the better say 0.1uF.
4. This should solve your problem.

The microphone module I use is AC coupled. Please let me know how you got on.
