### ISSUE TITLE
improve performance math for readVoltage() example

### ISSUE THREAD

**Issue by RobTillaart** [G6EJD/ESP32-ADC-Accuracy-Improvement-function#9]
As all powers used are integers one can use Horner's method to speed up the math.
- https://en.wikipedia.org/wiki/Horner%27s_method

equal amount of multiplications and additions, but no **pow()** function calls.

```cpp
double ReadVoltage(byte pin){
  double reading = analogRead(pin);  //  Reference voltage is 3v3 so maximum reading is 3v3 = 4095 in range 0 to 4095
  if (reading < 1 || reading > 4095) return 0;

  //  return -0.000000000009824 * pow(reading,3) + 0.000000016557283 * pow(reading,2) + 0.000854596860691 * reading + 0.065440348345433;

  //  return -0.000000000000016 * pow(reading,4) + 0.000000000118171 * pow(reading,3)- 0.000000301211691 * pow(reading,2)+ 0.001109019271794 * reading + 0.034143524634089;

  //  Added an improved polynomial, use either, comment out as required

  //  Use Horner's method to speed up the math
  return (((-0.000000000000016 * reading + 0.000000000118171) * reading - 0.000000301211691) * reading - 0.001109019271794 ) * reading + 0.034143524634089;
}
```

**Comment by G6EJD** [comment]
I don’t understand what you are eluding to here, your suggesting there is a code issue, but I don’t see any. If not a code issue then on GitHub there is provision for a comment.
The point about this function is to linearise an ADC reading when a battery voltage is read by the ESP32, where it is expected to be called occasionally, certainly not at high speed periodic intervals. 

Also, I don’t see any code example that implements a different technique, which for the vast majority of users would be nothing more than academic in nature.

Please explain, rather than making a statement that leads no-where.

**Comment by RobTillaart** [comment]
The last line of the function readvoltage() in my post has an performance optimized version of your code.

It is not a problem with your code, just an optimization.

It uses Horner's method of optimizing polynomes, not using the pow() function.
I have no hardware nearby to measure the actual gain or footprint diff.

And yes for battery management it doesn't matter. For other applications it might be useful.

Feel free to close the issue if it not matches your intent for this repo

**Comment by G6EJD** [comment]
As it happens, the compiler evaluates the POW() function results to a long-double anyway, so you method is of no value post compilation.
